import "Windows.Media.idl";

#include <sdkddkver.h>

namespace WPlayerVideoCodec
{
	[version(NTDDI_WINBLUE)]
	runtimeclass VideoDecoder
    {
		[default] interface Windows.Media.IMediaExtension;
    }
}